version: '3.5'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env_prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: employee_back

  web:
    build: .
    volumes:
      - ./:/app/
      - ./static:/app/static/
      - ./media:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: employee_web
    env_file:
      - .env_prod
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
